export enum FormGroupKeys {
  Assembly = 'assemblyFormGroup',
  Electronics = 'electronicsFormGroup',
  Machining = 'machiningFormGroup',
  CleaningForging = 'cleaningForgingFormGroup',
  BilletHeatingForging = 'billetHeatingForgingFormGroup',
  TrimmingHydraulicForging = 'trimmingHydraulicForgingFormGroup',
  StraighteningOptionalForging = 'straighteningOptionalForgingFormGroup',
  PiercingHydraulicForging = 'piercingHydraulicForgingFormGroup',
  TestingMpiForging = 'testingMpiForgingFormGroup',
  TubeBending = 'tubeBendingFormGroup',
  InsulationJacket = 'insulationJacketFormGroup',
  Brazing = 'brazingFormGroup',
  Casting = 'castingFormGroup',
  MetalExtrusion = 'metalExtrusionFormGroup',
  PlasticTubeExtrusion = 'plasticTubeExtrusionFormGroup',
  PlasticVacuumForming = 'plasticVacuumFormingFormGroup',
  CustomCable = 'customCableFormGroup',
  WiringHarness = 'wiringHarnessFormGroup',
  CompressionMolding = 'compressionMoldingFormGroup',
  ForgingSubProcess = 'forgingSubProcessFormGroup',
  Sustainability = 'sustainabilityFormGroup',
  SheetMetalProcess = 'sheetMetalProcessFormGroup',
}
