export { MaterialInformationPage } from '../db/material-information.page'
export { ManufacturingPage } from '../db/manufacturing.page'
export { WeldingPage } from './welding-calculator.page'
// export { ToolingPage } from './tooling.page'
export { MigWeldingPage } from './mig-welding.page'

export { ToolingPage } from './tooling.page'
export { ToolingLogic } from './tooling-logic'
export { PlasticRubberPage } from './plastic-rubber.page'
export { PlasticRubberLogic } from './plastic-rubber-logic'
export { MaterialTestingPage } from './material-testing.page'
export { ManufacturingTestingPage } from './manufacturing-testing.page'
export { StockMachiningTestingPage } from './stock-machining-testing.page'
export { ForgingTestingPage } from './forging-testing.page'
export { AssemblyTestingPage } from './assembly-testing.page'
export { ElectronicsTestingPage } from './electronics-testing.page'
export { CastingTestingPage } from './casting-testing.page'
export { ExtrusionTestingPage } from './extrusion-testing.page'
