export const homeEndpoints = {
  getProjectDetails: (base: string) => `${base}/costing/ProjectInfo?fullList=true`,
  getActiveProjectList: (base: string) => `${base}/costing/ProjectInfo/active`,
  getActiveProjectSearchList: (base: string) => `${base}/costing/ProjectInfo/active/search`,
  getPartThumbnailsAsync: (base: string) => `${base}/costing/ProjectInfo/active/projects/GetPartThumbnails`,
  getArchiveProjectList: (base: string) => `${base}/costing/ProjectInfo/archive`,
  getProjectNumber: (base: string) => `${base}/costing/Projects/GetProjectNumber`,
  getArchived: (base: string) => `${base}/costing/ProjectInfo/archive`,
  getProjectDetailById: (base: string, projectId: string) => `${base}/costing/ProjectInfo/${projectId}`,
  insertProjectinfo: (base: string) => `${base}/costing/Projects/createproject`,
  editArchived: (base: string, projectnumber: string) => `${base}/costing/ProjectInfo/archive?projectInfoId= ${projectnumber}`,
  restoreProject: (base: string, projectnumber: string) => `${base}/costing/ProjectInfo/restore?projectInfoId= ${projectnumber}`,
  postProjectinfo: (base: string) => `${base}/costing/Projects/Updateproject`,
  processBomTemplate: (base: string) => `${base}/costing/Projects/BOMTemplateProcess`,
  partsFilesProcess: (base: string) => `${base}/costing/Projects/PartsFilesProcess`,
  partsFileUpload: (base: string, projectName: string, partName: string) => `${base}/costing/Projects/PartsFileUpload?projectName=${projectName}&partName=${partName}`,
  updateParts: (base: string) => `${base}/costing/Projects/UpdateParts`,
  getProjectData: (base: string) => `${base}/costing/ProjectInfo`,
  getProjectDataById: (base: string, id: number) => `${base}/costing/ProjectInfo/${id}`,
  bomTemplateDownload: (base: string) => `${base}/templates/UploadTemplate.xlsx`,
  createVendor: (base: string) => `${base}/costing/Vendor/Create`,
  getVendorAll: (base: string) => `${base}/costing/Vendor/All`,
  getVendorByName: (base: string, name: string) => `${base}/costing/Vendor/${name}`,
  getBuLocation: (base: string) => `${base}/costing/BuLocation`,
  saveBuLocation: (base: string) => `${base}/costing/BuLocation`,

  getIndustry: (base: string) => `${base}/costing/Industry`,
  saveIndustry: (base: string) => `${base}/costing/Industry`,
  getDigitaFactory: (base: string, supplierId: number) => `${base}/costing/digitalfactory/${supplierId}/getAsync`,
  createDigitalFactory: (base: string) => `${base}/costing/digitalfactory/create`,
  updateDigitalFactory: (base: string, supplierId: number) => `${base}/costing/digitalfactory/${supplierId}/UpdateNewAsync`,
  createNewDigitalFactory: (base: string) => `${base}/costing/digitalfactory/createNew`,
  updateNewDigitalFactory: (base: string) => `${base}/costing/digitalfactory/updateNewAsync`,
  getNewDigitaFactoryBySupplierId: (base: string, supplierId: number) => `${base}/costing/digitalfactory/${supplierId}/getNewAsync`,
  getDfMaterialInfoByMarketMonth: (base: string, supplierId: number, materialMasterId: number, marketMonth: string) =>
    `${base}/costing/digitalfactory/getByMarketMonthAsync?supplierId=${supplierId}&materialMasterId=${materialMasterId}&marketMonth=${marketMonth}`,
  getDigitaFactorySuppliers: (base: string, pageNumber: number, pageSize: number) => `${base}/costing/digitalfactory/getDigitalFactorySuppliers?pageNumber=${pageNumber}&pageSize=${pageSize}`,
  getAllDigitalFactorySuppliers: (base: string) => `${base}/costing/digitalfactory/getAllDigitalFactorySuppliers`,
  removeFromDigitalFactoryById: (base: string, digitalFactoryId: number) => `${base}/costing/digitalfactory/${digitalFactoryId}/removeNewAsync`,
  addDfMaterialCostInfo: (base: string) => `${base}/costing/digitalfactory/addDfMaterial`,
  addDfMachineCostInfo: (base: string) => `${base}/costing/digitalfactory/addDfMachine`,
  removeDfMaterialCostInfo: (base: string) => `${base}/costing/digitalfactory/removeDfMaterial`,
  removeDfMachineCostInfo: (base: string) => `${base}/costing/digitalfactory/removeDfMachine`,
  updateDfMaterialCostInfo: (base: string) => `${base}/costing/digitalfactory/updateDfMaterial`,
  updateDfMachineCostInfo: (base: string) => `${base}/costing/digitalfactory/updateDfMachine`,
};
