export class BillOfMaterialDto {
  bomId: number;
  partInfoId: number;
  partQty: number;
  uom?: string;
  mfr?: string;
  mpn?: string;
  currentCost?: number;
  level?: number;
  isArchived: boolean;
  partWeight: number;
  primaryMaterial?: string;
  subCommodity?: number;
  technology?: string;
  pins?: string;
  tvhPrice?: number;
  parentPartNumber?: string;
  lifetimeRemainingYears: number;
  lifetimeQuantityUOM: number;
  isThisPartBeingPurchasedCurrently: boolean;
  currentSupplierName?: string;
  latestPricingNegotiation: Date;
  doYouHaveCostBreakdown: boolean;
  rawMaterialCost: number;
  conversionCost: number;
  overheadProfit: number;
  packaging: number;
  logistics: number;
  dutiesTariff: number;
  scenarioId: number;
  parentPartInfoId: number;
  unitOfMeasure?: string = null;
  standardOrCustom?: string = null;
  targetCost?: number;
  description: string = null;
  annualVolume?: number;
  annualSavingOpp?: number;
  partCategory?: string = null;
  extendedCost?: number;
  totalSubPartQty?: number;
  globalAnnualVolume?: number;
  mountingSide?: number;
  savingOpp?: number;
  shouldCost?: number;
  rpaCallRequired?: boolean;
  jSONData?: string;
  partMatch: number;
  isDirectMatch?: boolean;
  supplierName?: string;
  mfrName?: string;
  breakQuantity?: number;
  partialMatchMpn?: string;
  subCategoryName?: string;
  image?: string;
  lengthInFeet?: number;
  partStatus?: string;
  partStatusName?: string;
  isManuallyCreated?: boolean;
  isLoadingFromTemplate?: boolean;
  lengthHasValue?: boolean;
  categoryName?: string;
  series?: string;
  packagingType?: string;
  constructor() {
    this.parentPartNumber = '';
    this.currentSupplierName = '';
    this.latestPricingNegotiation = new Date('1900/01/01');
    this.rpaCallRequired = false;
  }
}
