import { MaterialCoreDetailsDto } from './Material-Core-Details.model';
import { MaterialMarketDataDto } from './material-market-data.model';
import { LaserCuttingTime } from './sheet-metal-lookup.model';
import { MaterialMasterDto } from './material-master.model';
import { ThermoForming } from './thermo-forming.models';

export class MaterialInfoDto {
  materialInfoId: number;
  partInfoId: number;
  materialMarketId?: number;
  materialMasterId?: number;
  materialDescription?: string;
  baseMaterialTypeId?: number;
  baseMaterialDescription?: number;
  processId: number;
  processName?: string;
  density: number;
  netWeight: number;
  netWeightPercentage: number;
  grossWeight: number;
  scrapWeight: number;
  materialYield: number;
  regrindAllowance: number;
  scrapRecovery: number;
  materialPricePerKg?: number;
  scrapPricePerKg?: number;
  esgImpactCO2Kg: number;
  totalEsgImpactCO2Kg: number;
  esgImpactCO2KgScrap: number;
  esgImpactCO2KgPart: number;
  esgAnnualVolumeKg: number;
  esgAnnualKgCO2: number;
  esgAnnualKgCO2Part: number;
  materialCostPart: number;
  materialGroupId: number;
  calculationMethod: string;
  dimX: number;
  dimY: number;
  dimZ: number;
  dimArea: number;
  dimVolume: number;
  partAllowance: number;
  utilisation: number;
  netMatCost: number;
  scrapRecCost: number;
  colorant: string;
  colorantPer: number;
  colorantCost: number;
  noOfCavities: number;
  partShape?: string;
  colorantPrice: number;
  runnerDia: number;
  runnerLength: number;
  runnerType: string;
  flowFactor: number;
  wallThickFactor: number;
  wallThickessMm: number;
  maxFlowlength: number;
  injPressure: number;
  projectedArea: number;
  calcTonn: number;
  txtWindows: number;
  closingTime: number;
  injectionTime: number;
  holdingTime: number;
  coolingTime: number;
  ejectionTime: number;
  pickPlaceTime: number;
  openingTime: number;
  totCycleTime: number;
  coilWidth?: number;
  coilLength?: number;
  enterStartEndScrapLength?: number;
  partsPerCoil?: number;
  coilWeight?: number;
  unfoldedSheetweight?: number;
  materialMarketData?: MaterialMarketDataDto;
  partFinish: number;
  noOfInserts: number;
  dataCompletionPercentage: number;
  partProjectedArea?: number;
  partVolume?: number;
  runnerProjectedArea?: number;
  runnerVolume?: number;
  volumePurchased?: number;
  partOuterDiameter?: number;
  partInnerDiameter?: number;
  partLength?: number;
  coilDiameter?: number;
  cuttingAllowance?: number;
  totalPartStockLength?: number;
  dimUnfoldedX: number;
  dimUnfoldedY: number;
  dimUnfoldedZ: number;
  secondaryProcessId?: number;
  machiningScrapPrice?: number;
  runnerRiser?: number;
  runnerRiserPercentage?: number;
  oxidationLossWeight?: number;
  oxidationLossWeightPercentage?: number;
  pouringWeight?: number;
  cavityArrangementLength?: number;
  cavityArrangementWidth?: number;
  totalPouringWeight?: number;
  moldBoxLength?: number;
  moldBoxHeight?: number;
  moldBoxWidth?: number;
  moldSandWeight?: number;
  sandRecovery?: number;
  sandRecoveryPercentage?: number;
  sandWeightAfterRecovery?: number;
  sandMetalRatio?: number;
  primaryCount?: number;
  primaryWeight?: number;
  primaryPrice?: number;
  secondaryCount?: number;
  secondaryWeight?: number;
  secondaryPrice?: number;
  cavityEnvelopLength?: number;
  cavityEnvelopWidth?: number;
  cavityEnvelopHeight?: number;
  boxVolume?: number;
  castingVolume?: number;
  coreVolume?: number;
  totalSandVolume?: number;
  totalCoreWeight?: number;
  machineScrapWeight?: number;
  wireDiameter?: number;
  beadSize?: number;
  totalWeldLength?: number;
  totalWeldBeadArea?: number;
  effeciency?: number;
  weldWeightWastage?: number;
  coreCostDetails?: MaterialCoreDetailsDto[];
  stockDiameter?: number;
  stockLength?: number;
  stockOuterDiameter?: number;
  stockInnerDiameter?: number;
  partWidth?: number;
  partHeight?: number;
  stockCrossSectionWidth?: number;
  stockCrossSectionHeight?: number;
  stockHexSideDimension?: number;
  blockLength?: number;
  blockWidth?: number;
  blockHeight?: number;
  stockCrossSectionArea?: number;
  stockType?: number;
  isStockTypeDirty?: boolean = false;
  lengthAllowance?: number;
  widthAllowance?: number;
  heightAllowance?: number;
  blankDiameter?: number;
  finalComponentDiameter?: number;
  partSurfaceArea?: number;
  unfoldedPartVolume?: number;
  diameterAllowance?: number;
  //for simulation
  shearingStrength?: number;
  runnerPartVolume?: number;
  runnerScrapWeight?: number;
  eav?: number;
  partStockLength?: number;
  materialDescriptionList?: MaterialMasterDto[];
  materialMasterData?: MaterialMasterDto;
  materialFamily?: number;
  sheetWeight?: number;
  laserCutttingTimeList?: LaserCuttingTime[];
  thermoFormingList?: ThermoForming[];
  materialInfoList?: MaterialInfoDto[];
  sandForCoreFormArray?: any[];
  stockHeight?: number;
  stockWidth?: number;
  inputBilletLength?: number;
  isInputBilletLengthDirty?: number;
  inputBilletWidth?: number;
  inputBilletHeight?: number;
  inputBilletDiameter?: number;
  sandCost?: number = 0;
  partTickness?: number = 0;
  typeOfWeld?: number = 0;
  typeOfMaterialBase?: number = 0;
  sheetLength?: number;
  sheetWidth?: number;
  sheetThickness?: number;
  wallAverageThickness?: number;
  maxWallthick?: number;
  standardDeviation?: number;
  weldLegLength?: number;
  isTypeOfMaterialBaseDirty?: boolean = false;
  isNoOfInsertsDirty?: boolean = false;
  isAvgWallthickDirty?: boolean = false;
  isMaxWallthickDirty?: boolean = false;
  isStdDeviationDirty?: boolean = false;
  iswireDiameterDirty?: boolean = false;
  machiningIsRod?: boolean = false;
  machiningIsBlock?: boolean = false;
  machiningIsWire?: boolean = false;
  machiningIsTube?: boolean = false;
  machiningIsSquareBar?: boolean = false;
  machiningIsRectangularBar?: boolean = false;
  machiningIsHexagonalBar?: boolean = false;
  machiningIsOtherShapes?: boolean = false;
  machiningIsLAngle?: boolean = false;
  machiningIsIBeam?: boolean = false;
  machiningIsChannel?: boolean = false;
  machiningIsWBeams?: boolean = false;
  machiningIsHss?: boolean = false;
  lotSize: number = 0;
  isNetweightDirty?: boolean = false;
  isNetweightPercentageDirty?: boolean = false;
  isRegrindAllowanceDirty?: boolean = false;
  isPartProjectedAreaDirty?: boolean = false;
  isPartSurfaceAreaDirty?: boolean = false;
  isProjectedAreaDirty?: boolean = false;
  isRunnerDiaDirty?: boolean = false;
  isRunnerLengthDirty?: boolean = false;
  isScrapWeightDirty?: boolean = false;
  isMatPriceDirty?: boolean = false;
  isScrapPriceDirty?: boolean = false;
  isRunnerTypeDirty?: boolean = false;
  isGrossWeightDirty?: boolean = false;
  isDensityDirty?: boolean = false;
  isUnbendPartWeightDirty?: boolean = false;
  isBlankDiameterDirty?: boolean = false;
  isFinalComponentDiameterDirty?: boolean = false;
  isInjectionTimeDirty?: boolean = false;
  isClosingTimeDirty?: boolean = false;
  isCoilDiameterDirty?: boolean = false;
  isCoilLengthDirty?: boolean = false;
  isCoilWeightDirty?: boolean = false;
  isCuttingAllowanceDirty?: boolean = false;
  isCoilWidthDirty?: boolean = false;
  isPartVolumeDirty?: boolean = false;
  isPartAllowanceDirty?: boolean = false;
  isPartsPerCoilDirty?: boolean = false;
  isGrossWeightCoilDirty?: boolean = false;
  isStartEndScrapLengthDirty?: boolean = false;
  isScrapRecoveryDirty?: boolean = false;
  isMachiningScrapPriceDirty?: boolean = false;
  isMachiningScrapWeightDirty?: boolean = false;
  isNoOfCavitiesDirty?: boolean = false;
  isCavityArrangementLengthDirty?: boolean = false;
  isCavityArrangementWidthDirty?: boolean = false;
  isRunnerRiserDirty?: boolean = false;
  isRunnerRiserPercentageDirty?: boolean = false;
  isOxidationLossWeightDirty?: boolean = false;
  isOxidationLossWeightPercentageDirty?: boolean = false;
  isPouringWeightDirty?: boolean = false;
  isTotalPouringWeightDirty?: boolean = false;
  isSandRecoveryDirty?: boolean = false;
  isSandRecoveryPercentageDirty?: boolean = false;
  isMoldBoxLengthDirty?: boolean = false;
  isMoldBoxHeightDirty?: boolean = false;
  isMoldBoxWidthDirty?: boolean = false;
  isBoxVolumeDirty?: boolean = false;
  isCoreVolumeDirty?: boolean = false;
  isTotalSandVolumeDirty?: boolean = false;
  isMoldSandWeightDirty?: boolean = false;
  isSandWeightAfterRecoveryDirty?: boolean = false;
  isPrimaryCountDirty?: boolean = false;
  isPrimaryWeightDirty?: boolean = false;
  isPrimaryPriceDirty?: boolean = false;
  isSecondaryCountDirty?: boolean = false;
  isSecondaryWeightDirty?: boolean = false;
  isSecondaryPriceDirty?: boolean = false;
  isStockDiameterDirty?: boolean = false;
  isStockOuterDiameterDirty?: boolean = false;
  isStockInnerDiameterDirty?: boolean = false;
  isStockCrossSectionWidthDirty?: boolean = false;
  isStockCrossSectionHeightDirty?: boolean = false;
  isCavityEnvelopLengthDirty?: boolean = false;
  isCavityEnvelopWidthDirty?: boolean = false;
  isCavityEnvelopHeightDirty?: boolean = false;
  isCastingVolumeDirty?: boolean = false;
  isEffeciencyDirty?: boolean = false;
  isTotalWeldBeadAreaDirty?: boolean = false;
  isTotalWeldLengthDirty?: boolean = false;
  isWeldWeightWastageDirty?: boolean = false;
  isTotalCoreWeightDirty?: boolean = false;
  isStockLengthDirty?: boolean = false;
  isTypeOfCableDirty?: boolean = false;
  isTypeOfWeldDirty?: boolean = false;
  isStockHeightDirty?: boolean = false;
  isStockWidthDirty?: boolean = false;
  isEsgImpactCO2KgDirty?: boolean = false;
  isEsgImpactCO2KgScrapDirty?: boolean = false;
  isEsgImpactCO2KgPartDirty?: boolean = false;
  ispaintAreaDirty?: boolean = false;
  ispaintCoatingTicknessDirty?: boolean = false;
  ispartTicknessDirty?: boolean = false;
  istotalPaintCostsqmDirty?: boolean = false;
  isdiameterAllowanceDirty?: boolean = false;
  isSheetLengthDirty?: boolean = false;
  isSheetWidthDirty?: boolean = false;
  isSheetThicknessDirty?: boolean = false;
  isutilisationDirty?: boolean = false;
  isprimerMatPriceDirty?: boolean = false;
  isprimerCoatingTicknessDirty?: boolean = false;
  isprimerNetWeightDirty?: boolean = false;
  isprimerDensityDirty?: boolean = false;
  isPartOuterDiameterDirty: boolean = false;
  isPartInnerDiameterDirty: boolean = false;
  isPartLengthDirty: boolean = false;
  isPartWidthDirty: boolean = false;
  isPartHeightDirty: boolean = false;
  isStockHexSideDimensionDirty: boolean = false;
  isEnterStartEndScrapLengthDirty: boolean = false;
  isPercentageOfReductionDirty: boolean = false;
  isNoOfDrawStepsDirty: boolean = false;
  isColorantDirty?: boolean = false;
  isColorantPerDirty?: boolean = false;
  isColorantCostDirty?: boolean = false;
  isColorantPriceDirty?: boolean = false;
  isFlowFactorDirty?: boolean = false;
  isWallThickFactorDirty?: boolean = false;
  isMaxFlowlengthDirty?: boolean = false;
  isInjPressureDirty?: boolean = false;
  isPartShapeDirty?: boolean = false;

  countryId?: number;
  countryName?: string;
  volumeDiscountPer?: number;
  unbendPartWeight?: number;
  stockForm?: string;
  paintArea?: number;
  paintCoatingTickness?: number;
  totalPaintCostsqm?: number;
  primerMatPrice?: number;
  primerCoatingTickness?: number;
  primerNetWeight?: number;
  primerDensity?: number;
  coatingThickness?: number;
  categoryId?: number;

  typeOfCable?: number;
  typeOfConductor?: number;
  numOfConductors?: number;
  totalCableLength?: number;
  noOfCables?: number;
  noOfCablesWithSameDia?: number;
  mainInsulatorID?: number;
  mainInsulatorOD?: number;
  mainCableSheathingMaterial?: number;
  percentageOfReduction?: number;
  noOfDrawSteps?: number;
  isTotalCableLengthDirty: boolean = false;
  pitchForWireCutting?: number;
  isPitchForWireCutting: boolean = false;
  isUnfoldedLength: boolean = false;

  totalCostOfRawMaterials?: number;
  perimeter?: number;
  flashVolume?: number;
  scaleLoss?: number;
  grossVolumne?: number;
  yeildUtilization?: number;
  ultimateTensileStrength?: number;
  cuttingLoss?: number;
  isTotalCostOfRawMaterialsDirty?: boolean = false;
  isPerimeterDirty?: boolean = false;
  isFlashVolumeDirty?: boolean = false;
  isScaleLossDirty?: boolean = false;
  isGrossVolumneDirty?: boolean = false;
  isYeildUtilizationDirty?: boolean = false;
  isUltimateTensileStrength?: boolean = false;
  isCuttingLoss?: boolean = false;
  isBlockLengthDirty?: boolean = false;
  isInputBilletDiameterDirty: boolean = false;
  isVolumePurchasedDirty: boolean = false;
  isAiSuggested: boolean = false;
  oneMtDiscount?: number;
  twentyFiveMtDiscount?: number;
  fiftyMtDiscount?: number;
  matPriceGross?: number;
  isCoatingThicknessDirty: boolean = false;
  isPrimerCoatingTicknessDirty: boolean = false;
  createDate: Date;
  laminatesList?: any[];
  prepregList?: any[];
}
