import { CountryDataMasterDto } from './country-data-master.model';
import { DrillingCutting } from './drilling-cutting.model';
import { ForgingLookupDto } from './forging.model';
import { MaterialInfoDto } from './material-info.model';
import { MaterialMasterDto } from './material-master.model';
import { MachineMarketDto, MedbMachinesMasterDto } from './medb-machine.model';
import { MigWeldingLookupDto } from './migLookup.model';
import { HandlingTime, LaserCuttingTime, PlasmaCutting, StrokeRate, StrokeRateManual, ToolLoadingTime } from './sheet-metal-lookup.model';
import { SubProcessTypeInfoDto } from './subprocess-info.model';
import { CostToolingDto } from './tooling.model';
import { TurningInfoDto } from './turning-info.model';
import { FacingDto } from './facing-info.model';
// import { GroovingLookupDto } from './grooving-lookup.model';
import { Milling } from './machining-milling.model';
import { Grinding } from './machining-grinding.model';
import { GearCutting } from './machining-gearcutting.model';
import { PartingCuttingDto } from './parting-cutting.modal';
import { FormingTime, ThermoForming } from './thermo-forming.models';
import { WiringHarness } from './wiring-harness.model';
import { Boring } from './machining-boring.model';
import { PartInfoDto } from './part-info.model';
import { LaborRateMasterDto } from './labor-rate-master.model';
import { CommentFieldFormIdentifierModel } from './comment-field-model';
import { FieldColorsDto } from './field-colors.model';

type FormArray<T> = T[];

export class ReCalculateContext {
  calculateResults: ProcessInfoDto[] = [];
  materialInfoList: MaterialInfoDto[] = [];
  currentPart: PartInfoDto | undefined;
  automationProcessCount: number = 0;
  selectedProcessInfoId: number = 0;
  formIdentifier: CommentFieldFormIdentifierModel | undefined;
  selectedProcess: ProcessInfoDto | undefined;
  dirtyFields: FieldColorsDto[] = [];
  laborRate: LaborRateMasterDto[] = [];
  isToolingNeedToRun: boolean = false;
}

export class ProcessInfoDto {
  projectInfoId: number = 0;
  processId: number = 0;
  processName?: string;
  processInfoId: number = 0;
  partInfoId: number = 0;
  machineId?: number;
  machineMarketId?: number;
  machineMaster: MedbMachinesMasterDto = {} as MedbMachinesMasterDto;
  semiAutoOrAuto: number = 0;
  sortOrder: number = 0;
  noOfImpressionsOrCavities: number = 0;
  cycleTime: number = 0;
  setUpTime: number = 0;
  noOfLowSkilledLabours: number = 0;
  noOfSkilledLabours: number = 0;
  noOfSemiSkilledLabours: number = 0;
  lowSkilledLaborRatePerHour: number = 0;
  skilledLaborRatePerHour: number = 0;
  machineHourRate: number = 0;
  machineHourRateFromDB: number = 0;
  min: number = 0;
  max: number = 0;
  commodityTypeId: number = 0;
  directLaborCost: number = 0;
  directMachineCost: number = 0;
  directSetUpCost: number = 0;
  directTooling: number = 0;
  yieldPer: number = 0;
  yieldCost: number = 0;
  inspectionTime: number = 0;
  inspectionCost: number = 0;
  directProcessCost: number = 0;
  machineMarket?: MachineMarketDto;
  selectedTonnage?: number;
  dataCompletionPercentage: number = 0;
  recommendTonnage?: number;
  recommendedForce?: number;
  totalToolLendingTime?: number;
  sheetLoadUloadTime?: number;
  isSheetLoadULoadTimeDirty?: boolean = false;
  theoreticalForce?: number;
  noOfbends?: number;
  isNoOfBends?: number;
  totalTonnageRequired?: number;
  isTotalTonnageRequiredDirty?: boolean = false;
  bendingLineLength?: number;
  isBendingLineLengthDirty?: boolean = false;
  shoulderWidth?: number;
  bendingCoeffecient?: number;
  ultimateTensileMaterial?: number;
  lineOfInspector?: number;
  qaOfInspector?: number;
  lineOfInspectorRate?: number;
  qaOfInspectorRate?: number;
  netGoodParts?: number;
  lengthOfCut?: number;
  totalDepOfCut?: number;
  shearStrengthMaterial?: number;
  cuttingLength?: number;
  noOfStartsPierce?: number;
  cuttingSpeed?: number = 0;
  cuttingTime?: number;
  isCuttingTimeDirty?: boolean = false;
  piercingTime?: number;
  totalTime?: number;
  samplingRate?: number;
  machineDescription: string = '';
  processType: string = '';
  machineType: string = '';
  insertsPlacement?: number;
  sideCoreMechanisms?: number;
  moldClosing?: number;
  materialInjectionFillTime?: number;
  injectionHoldingTime?: number;
  moldOpening?: number;
  partEjection?: number;
  others?: number;
  dryCycleTime?: number;
  injectionPressure?: number;
  qaInspectionCostPerHr?: number;
  lineInspectorCostPerHr?: number;
  formLength?: number;
  formHeight?: number;
  totalElectricityConsumption: number = 0;
  esgImpactElectricityConsumption: number = 0;
  totalFactorySpaceRequired: number = 0;
  esgImpactFactoryImpact: number = 0;
  esgImpactAnnualUsageHrs: number = 0;
  esgImpactAnnualKgCO2: number = 0;
  esgImpactAnnualKgCO2Part: number = 0;
  hlFactor?: number;
  subProcessTypeID?: number;
  coolingTime?: number;
  setUpCost?: number;
  inspectionType?: number;
  inspectionLevel?: number;
  workpieceStockDiameter?: number;
  workpieceStockLength?: number;
  noOfHitsRequired?: number;
  feedPerRev?: number;
  spindleRpm?: number;
  drillDiameter?: number;
  drillDepth?: number;
  processTypeID?: number;
  machineTypeId?: number;
  formPerimeter?: number;
  subProcessTypeInfos?: SubProcessTypeInfoDto[];
  moldMaking?: number;
  corePlacement?: number;
  shakeout?: number;
  sandShooting?: number;
  gasingVenting?: number;
  efficiency?: number;
  totalCycleTime?: number;
  noOfParts?: number;
  powerSupply?: number;
  meltingPower?: number;
  totalMeltingTime?: number;
  chargeIntoFurance?: number;
  liquidMetalTransfer?: number;
  idleTimeMelt?: number;
  idleTimeMouldBox?: number;
  efficiencyFactor?: number;
  gravitationalAccelaration?: number;
  effectiveMetalHead?: number;
  machcineCapacity?: number;
  utilisation?: number;
  newToolingRequired: boolean = false;
  costTooling?: CostToolingDto;
  workCenterId?: number;
  totalPowerCost?: number;
  totalGasCost?: number;
  muffleLength?: number;
  muffleWidth?: number;
  furanceEfficiency?: number;
  initialTemp?: number;
  finalTemp?: number;
  partEnvelopHeight?: number;
  initialStockHeight?: number;
  punchPerimeter?: number;
  soakingTime?: number;
  forgingShapeFactor?: number;
  partArea?: number;
  flashArea?: number;
  flashThickness?: number;
  cuttingArea?: number;
  furnaceOutput?: number;
  meltingWeight?: number;
  allowanceBetweenParts?: number;
  allowanceAlongLength?: number;
  allowanceAlongWidth?: number;
  platenSizeLength?: number;
  platenSizeWidth?: number;
  shotSize?: number;
  clampingPressure?: number;
  injectionTemp?: number;
  liquidTemp?: number;
  moldTemp?: number;
  coolingFactor?: number;
  injectionRate?: number;
  dieClosingTime?: number;
  totalInjectionTime?: number;
  pouringTime?: number;
  dieOpeningTime?: number;
  partExtractionTime?: number;
  lubeTime?: number;
  yieldTimeLoss?: number;
  wireGuage?: number;
  noOfWireCableCutting?: number;
  wireCuttingStrippingSpeed?: number;
  noofStroke?: number;
  noOfCore?: number;
  noOfWireOrCrimp?: number;
  noOfConnector?: number;
  moldedPartCost?: number;
  lengthOfCable?: number;
  noOfCable?: number;
  noOfStamping?: number;
  cycleTimeSolderingJoint?: number;
  pricePerWet?: number;
  pricePerthinner?: number;
  ratioCoatingthinner?: number;
  lengthOfCoated?: number;
  widthOfCoated?: number;
  coatingthickness?: number;
  solidPercentageCoating?: number;
  appliedPerCentagethin?: number;
  appliedthinnerDollars?: number;
  timeReqPickPlace?: number;
  timeReqClampFixing?: number;
  timeReqRollTape?: number;
  noOfROllReq?: number;
  noOfCableTie?: number;
  noOfLabel?: number;
  addAssemblyTime?: number;
  noOfJointRequired?: number;
  timeRequiredCableTie?: number;
  cycleTimeLabelRequired?: number;
  noOfBendsPerXAxis?: number;
  noOfBendsPerYAxis?: number;
  noOfBendsPerZAxis?: number;
  wireTwistingSpeed?: number;
  isWireTwistingSpeedDirty?: boolean = false;
  packAndHoldTime?: number;
  lengthOfCutInternal?: number;
  noOfHoles?: number;
  loadingTime?: number;
  processTime?: number;
  rotationTime?: number;
  unloadingTime?: number;
  innerRadius?: number;
  partThickness?: number;
  dieOpeningThickness?: number;
  formingForce?: number;
  blankArea?: number;
  injectionTime?: number;
  ejectionUnloadingTime?: number;
  //simulation model//
  density?: number;
  thermalDiffusivity?: number;
  thermalConductivity?: number;
  specificHeatCapacity?: number;
  noOfInsert?: number;
  insertPlacement?: number;
  grossWeight?: number;
  materialInjFilltime?: number;
  partComplexity?: number;
  wallAverageThickness?: number;
  meltTemp?: number;
  ejecTemp?: number;
  mouldTemp?: number;
  lotSize?: number;
  noOfCavities?: number;
  netMaterialCost?: number;
  netPartWeight?: number;
  rawmaterialCost?: number;
  projArea?: number;
  partProjArea?: number;
  cavityPressure?: number;
  conversionCost?: number;
  partCost?: number;
  setUpTimeBatch?: number;
  totalToolLoadingTime?: number;
  mfrCountryId?: number;
  argonGasCost?: number;
  co2GasCost?: number;
  furnaceCapacityTon?: number;
  machineCapacity?: number;
  drawSpeed?: number;
  laserCutttingTimeList: LaserCuttingTime[] = [];
  plasmaCutttingSpeedList: PlasmaCutting[] = [];
  countryList: CountryDataMasterDto[] = [];
  MigLookupList: MigWeldingLookupDto[] = [];
  materialInfoList?: MaterialInfoDto[];
  coilALoadingUnloadingTime?: number;
  coilBLoadingUnloadingTime?: number;
  drillingCuttingSpeedList?: DrillingCutting[];
  strokeRateManualList?: StrokeRateManual[];
  wiringHarnessLookupList?: WiringHarness[];
  machineList?: MedbMachinesMasterDto[];
  materialType?: number;
  materialTypeName?: string;
  setupPercentage?: number;
  thickness?: number;
  strokeRateList: StrokeRate[] = [];
  handlingTimeList: HandlingTime[] = [];
  toolLoadingTimeList: ToolLoadingTime[] = [];
  materialmasterDatas: MaterialMasterDto = {} as MaterialMasterDto;
  processInfoList: ProcessInfoDto[] = [];
  forgingLookupList: ForgingLookupDto[] = [];
  runnerAllowance?: number;
  speedOfConveyer?: number;
  processDetails?: string;
  featureDetails?: string;
  bourdanRate?: number;
  requiredCurrent?: number;
  requiredWeldingVoltage?: number;
  weldingPosition?: number = 0;
  noOfIntermediateStartAndStop?: number;
  noOfTackWeld?: number;
  noOfWeldPasses?: number;
  travelSpeed?: number;
  powerConsumption?: number;
  electricityUnitCost?: number;
  isMachcineCapacityDirty?: boolean = false;
  isSemiAutoOrAutoDirty?: boolean = false;
  isselectedTonnageDirty?: boolean = false;
  isrequiredCurrentDirty?: boolean = false;
  isrequiredWeldingVoltageDirty?: boolean = false;
  isnoOfIntermediateStartAndStopDirty?: boolean = false;
  isnoOfTackWeldDirty?: boolean = false;
  isnoOfWeldPassesDirty?: boolean = false;
  istravelSpeedDirty?: boolean = false;
  ispowerConsumptionDirty?: boolean = false;
  iselectricityUnitCostDirty?: boolean = false;
  isbourdanRateDirty?: boolean = false;
  isspeedOfConveyerDirty?: boolean = false;
  iscuttingAreaDirty?: boolean = false;
  iscorePlacementDirty?: boolean = false;
  ismoldMakingDirty?: boolean = false;
  isshakeoutDirty?: boolean = false;
  isspindleRpmDirty?: boolean = false;
  ispunchPerimeterDirty?: boolean = false;
  isflashThicknessDirty?: boolean = false;
  istotalMeltingTimeDirty?: boolean = false;
  isutilisationDirty?: boolean = false;
  isnetGoodPartsDirty?: boolean = false;
  issetUpTimeDirty?: boolean = false;
  isefficiencyDirty?: boolean = false;
  isinspectionTimeDirty?: boolean = false;
  iscoolingTimeDirty?: boolean = false;
  isnoOfCoreDirty?: boolean = false;
  iscycleTimeDirty?: boolean = false;
  isdirectMachineCostDirty?: boolean = false;
  isdirectLaborCostDirty?: boolean = false;
  isdirectSetUpCostDirty?: boolean = false;
  isinspectionCostDirty?: boolean = false;
  isyieldCostDirty?: boolean = false;
  isyieldPercentDirty?: boolean = false;
  iscuttingSpeedDirty?: boolean = false;
  isfeedPerRevDirty?: boolean = false;
  ishlFactorDirty?: boolean = false;
  isallowanceBetweenPartsDirty?: boolean = false;
  ischargeIntoFuranceDirty?: boolean = false;
  istotalCycleTimeDirty?: boolean = false;
  isliquidMetalTransferDirty?: boolean = false;
  isallowanceAlongLengthDirty?: boolean = false;
  isallowanceAlongWidthDirty?: boolean = false;
  issandShootingDirty?: boolean = false;
  islengthOfCoatedDirty?: boolean = false;
  iswidthOfCoatedDirty?: boolean = false;
  isplatenSizeLengthDirty?: boolean = false;
  isplatenSizeWidthDirty?: boolean = false;
  istimeRequiredCableTieDirty?: boolean = false;
  ismoldedPartCostDirty?: boolean = false;
  isnoOfPartsDirty?: boolean = false;
  isshotSizeDirty?: boolean = false;
  isflashAreaDirty?: boolean = false;
  isclampingPressureDirty?: boolean = false;
  isrecommendedForceDirty?: boolean = false;
  isinjectionTempDirty?: boolean = false;
  isliquidTempDirty?: boolean = false;
  ismoldTempDirty?: boolean = false;
  iscoolingFactorDirty?: boolean = false;
  isNoOfCoreDirty?: boolean = false;
  isinjectionRateDirty?: boolean = false;
  isdieClosingTimeDirty?: boolean = false;
  istotalInjectionTimeDirty?: boolean = false;
  ispouringTimeDirty?: boolean = false;
  isdieOpeningTimeDirty?: boolean = false;
  ispartExtractionTimeDirty?: boolean = false;
  isfinalTempDirty?: boolean = false;
  issoakingTimeDirty?: boolean = false;
  islubeTimeDirty?: boolean = false;
  isyieldTimeLossDirty?: boolean = false;
  ispartEnvelopHeightDirty?: boolean = false;
  isinitialStockHeightDirty?: boolean = false;
  isforgingShapeFactorDirty?: boolean = false;
  ispartAreaDirty?: boolean = false;
  ismeltingWeightDirty?: boolean = false;
  issubProcessTypeIDDirty?: boolean = false;
  isfurnaceOutputDirty?: boolean = false;
  isesgImpactElectricityConsumptionDirty?: boolean = false;
  isesgImpactFactoryImpactDirty?: boolean = false;
  isSamplingRateDirty?: boolean = false;
  isQaInspectorRateDirty?: boolean = false;
  isLowSkilledLaborRatePerHourDirty?: boolean = false;
  isSkilledLaborRatePerHourDirty?: boolean = false;
  isNoOfLowSkilledLaboursDirty?: boolean = false;
  ismachineHourRateDirty?: boolean = false;
  isLengthOfCutInternalDirty?: boolean = false;
  isNoOfHolesDirty?: boolean = false;
  isNoOfStrokesDirty?: boolean = false;
  isLoadingTimeDirty?: boolean = false;
  isProcessTimeDirty?: boolean = false;
  isRotationTimeDirty?: boolean = false;
  isUnloadingTimeDirty?: boolean = false;
  isDirectToolingDirty?: boolean = false;
  isDrawSpeedDirty?: boolean = false;
  isDieOpeningThicknessDirty?: boolean = false;
  isInsertsPlacementDirty?: boolean = false;
  isPartEjectionDirty?: boolean = false;
  isSideCoreMechanismsDirty?: boolean = false;
  isOthersDirty?: boolean = false;
  isDryCycleTimeDirty?: boolean = false;
  isinjectionTimeDirty?: boolean = false;
  isejectionUnloadingTimeDirty?: boolean = false;
  isTotalFactorySpaceRequiredDirty?: boolean = false;
  isLengthOfCableDirty?: boolean = false;
  materialInfo?: MaterialInfo;
  machiningOperationTypeFormArray?: FormArray<any>;
  subProcessFormArray?: FormArray<any>;
  MachiningFlags: MachiningFlags = new MachiningFlags();
  turningLookupList: TurningInfoDto[] = [];
  facingLookupList: FacingDto[] = [];
  // groovingLookupList: GroovingLookupDto[] = [];
  millingLookupList: Milling[] = [];
  SlotMillingLookupList: any[] = [];
  endMillingLookupList: any[] = [];
  boringLookupList: Boring[] = [];
  grindingLookupList: Grinding[] = [];
  GearCuttingLookupList: GearCutting[] = [];
  partingCuttingSpeedList: PartingCuttingDto[] = [];
  thermoFormingList: ThermoForming[] = [];
  formingTimeList: FormingTime[] = [];
  countryId?: number;
  countryName?: string;
  coreCycleTimes?: any;
  isCoreCycleTimesDirty?: boolean[] = [];
  machineStrokes?: number;
  stitchingCycleTime?: number;
  eolInspectionSamplingRate?: number;
  noOfStitchingStationsRequired?: number;
  totalPinPopulation?: number;
  noOfTypesOfPins?: number;
  maxBomQuantityOfIndividualPinTypes?: number;
  typeOfOperationId: number = 0;
  recBedSize: string = '';
  selectedBedSize: string = '';
  recommendedDimension?: string;
  selectedDimension?: string;

  isMachineStrokesDirty: boolean = false;
  isStitchingCycleTime: boolean = false;
  isEOLInspectionSamplingRate: boolean = false;
  isNoOfStitchingStationsRequired: boolean = false;
  isTotalPinPopulation: boolean = false;
  isNoOfTypesOfPins: boolean = false;
  isMaxBomQuantityOfIndividualPinTypes: boolean = false;

  isDrillDiameterDirty: boolean = false;
  isCuttingLengthDirty: boolean = false;
  isTotalTimeDirty: boolean = false;
  isTheoreticalForceDirty: boolean = false;
  isMuffleLengthDirty: boolean = false;
  isMuffleWidthDirty: boolean = false;
  isNoOfHitsRequiredDirty: boolean = false;
  isNoOfStartsPierceDirty: boolean = false;
  isNoOfWeldPassesDirty: boolean = false;
  isEfficiencyFactorDirty: boolean = false;
  isLengthOfCutDirty: boolean = false;
  isNoOfWireCableCuttingDirty: boolean = false;
  isWorkpieceStockLengthDirty: boolean = false;
  isWorkpieceStockDiameterDirty: boolean = false;
  isUltimateTensileMaterialDirty: boolean = false;
  isShearStrengthMaterialDirty: boolean = false;
  isformHeightDirty: boolean = false;
  isWeldingPositionDirty: boolean = false;
  isTypeOfOperationDirty: boolean = false;
  isPowerSupplyDirty: boolean = false;
  isInitialTempDirty: boolean = false;
  isRecommendTonnageDirty: boolean = false;
  isBendingCoeffecientDirty: boolean = false;
  isWireCuttingStrippingSpeedDirty: boolean = false;
  isDrillDepthDirty: boolean = false;
  eav?: number;
  isMoldOpeningDirty: boolean = false;
  isFormPerimeterDirty: boolean = false;
  isBlankAreaDirty: boolean = false;
}

export class MachiningFlags {
  isDrilling: boolean = false;
  isMilling: boolean = false;
  isTurning: boolean = false;
  // isGrinding: boolean = false;
  isSurfaceGrinding: boolean = false;
  isCylindricalGrinding: boolean = false;
  isCenterlessGrinding: boolean = false;
  isBoring: boolean = false;
  isGearCutting: boolean = false;
  isGearBroaching: boolean = false;
  isGearSplineRolling: boolean = false;
  isGearShaving: boolean = false;
  isGearGrinding: boolean = false;
  // isVerticalBoring: boolean =  boolean = false;
}

export class MaterialInfo {
  weight: number = 0;
  scrapPrice: number = 0;
  totalCost: number = 0;
}
