export enum IMProcessGroup {
    MoldDesign = 1,
    MachineOperations = 2,
    Validation = 3,
    TextureCost = 4,
}

export enum SheetMetalProcessGroup {
    MoldDesign = 1,
    Programming = 2,
    MachineOperations = 3,
    MachinePlishing = 4,
    ToolHardening = 5,
    Assembly = 6,
    ToolTrialCost = 7,
    Validation = 8,
}

export enum CommodityType {
    PlasticAndRubber = 1,
    SheetMetal = 2,
    Casting = 3,
    StockMachining = 4,
    MetalForming = 5,
    Extrusion = 6,
    AdditiveManufacturing = 7,
    PCBAQuickCosting = 8,
    Electricals = 9,
    Others = 10,
    Testing = 11,
    Assembly = 12,
    WiringHarness = 14,
    Electronics = 15,
    PrintedCircuitBoard = 16,
}

export enum PartComplexity {
    High = 3,
    Medium = 2,
    Low = 1,
}

export enum MaterialCategory {
    Glass = 1,
    Plastics = 2,
    Foam = 3,
    PlasticFilm = 4,
    Chemicals = 5,
    NonFerrous = 6,
    PaintPowderGasSand = 7,
    Fabric = 8,
    Packaging = 9,
    PackagingConfig = 10,
    Ferrous = 11,
    Rubber = 12,
    Other = 13,
}

export enum ProcessType {
    //manufacturing
    BlowMolding = 1,
    Boring = 2,
    CenterlessGrinding = 4,
    ClosedDieForging = 5,
    ColdHeading = 6,
    CompressionMolding = 7,
    CylindricalGrinding = 8,
    Deburring = 9,
    Deflash = 10,
    DieCutTrim = 11,
    DiePenetrationTesting = 12,
    Drilling = 13,
    DrillingCenter = 113,
    FixtureInspection = 14,
    FrictionWelding = 15,
    //Gearhobbing = 16,
    GravityDieCasting = 17,
    GreenSandCasting = 18,
    HeatStaking = 19,
    HighPressureDieCasting = 20,
    Honning = 21,
    HotClosedDieForging = 22,
    HotOpenDieForging = 23,
    HotRingForging = 24,
    InjectionMouldingDoubleShot = 25,
    InjectionMouldingSingleShot = 26,
    InvestmentCasting = 27,
    Lapping = 28,
    LaserCutting = 29,
    LaserEtching = 30,
    LaserMarking = 31,
    LaserWelding = 32,
    LeakTesting = 33,
    IonicWashing = 159,
    IonicTesting = 160,
    LowPressureDieCasting = 34,
    ManualInspection = 35,
    MaterialComposisition = 36,
    MechanicalJoints = 37,
    MetalTubeExtrusion = 38,
    InductionHeatingMachine = 204,
    RollingStraightening = 205,
    EddyCurrentTesting = 206,
    BrightAnnealing = 207,
    Milling = 40,
    MillingCenter = 114,
    GrindingCenter = 115,
    GearCutting = 16,
    GearBroaching = 3,
    GearSplineRolling = 193,
    GearShaving = 194,
    GearGrinding = 195,
    OxyCutting = 41,
    PlasmaCutting = 43,
    PlasticExtrusion = 44,
    Plating = 45,
    PowderCoating = 46,
    ZincPlating = 130,
    ChromePlating = 131,
    NickelPlating = 143,
    TinPlating = 144,
    GoldPlating = 156,
    SilverPlating = 157,
    R2RPlating = 251,
    PressureTesting = 47,
    Printing = 48,
    Progressive = 49,
    RadiographyTesting = 50,
    RollForming = 51,
    RotorMolding = 52,
    RubberMaterialPreparation = 53,
    RubberVulcanization = 54,
    SaltSprayTesting = 55,
    ShellCasting = 56,
    ShotBlasting = 79,
    Sonicwelding = 58,
    SpotWelding = 59,
    MigWelding = 39,
    StickWelding = 209,
    SpringWireforming = 60,
    Stage = 61,
    SubMergedArcWelding = 62,
    SurfaceGrinding = 63,
    Tapping = 64,
    ThermoForming = 65,
    ThreadRolling = 66,
    TigWelding = 67,
    TransferMolding = 68,
    Turning = 69,
    TurningCenter = 112,
    TurretTPP = 70,
    UltrasonicTesting = 71,
    // VacuumForming = 72,
    VisualInspection = 73,
    WaterJetCutTrim = 74,
    WaterJetCutting = 75,
    Wrapping = 76,
    Bending = 99,
    MetalForming = 81,
    BandSaw = 82,
    RunnerRiserDegating = 83,
    PartCoolingShakeOut = 84,
    VaccumeImpregnation = 85,
    CorePreparation = 86,
    // HPDCMelting = 87, // not in db
    Cleaning = 88,
    CleaningCasting = 222,
    SawCutting = 89,
    StockHeating = 90,
    HeatTreatment = 122,
    TrimmingPress = 91,
    Machining = 92,
    CableWireCutting = 93,
    CableWireCrimping = 94,
    CableConnector = 95,
    CableInjectionMolding = 96,
    CableOverMolding = 97,
    CableWireTwisting = 98,
    CableBending = 80,
    CableStampingProcess = 100,
    CableSolderingProcess = 101,
    CablePottingProcess = 102,
    CableRoutingLine = 103,
    CableUltrasonicWelding = 104,
    CableHeatShrinkingTubing = 105,
    CableTieProcess = 106,
    CableLabeling = 107,
    Drawing = 108,
    StockShearing = 111,
    MoldPerparation = 116,
    Others = 120,
    Forming = 121,
    Assembly = 123,
    CablePreparation = 124,
    LineAssembly = 125,
    FinalInspection = 126,
    Painting = 42,
    // Paint = 128,
    Dry = 129,
    WetPainting = 127,
    SiliconCoatingAuto = 178,
    SiliconCoatingSemi = 179,
    Galvanization = 180,
    CastingCorePreparation = 141,
    CastingCoreAssembly = 142,
    PouringCasting = 77,
    MeltingCasting = 78,
    // CastingPouring = 137,
    // CastingMelting = 134,
    CastingMoldMaking = 135,
    CastingMoldAssembly = 136,
    CastingShakeout = 138,
    CastingDegating = 139,
    // CastingShotblasting = 140,
    CastingFettling = 133,
    MetullurgicalInspection = 132,

    WaxInjectionMolding = 167,
    TreePatternAssembly = 168,
    SlurryCoating = 169,
    Dewaxing = 170,
    ShellMoldFiring = 171,
    MoldKnockout = 172,

    CustomCableDrawing = 145,
    CustomCableAnnealing = 146,
    CustomCableThinning = 147,
    CustomCableTensionStreach = 148,
    CustomCableExtruder = 149,
    CustomCableDiameterControl = 150,
    CustomCableCoreLayUp = 151,
    CustomCableSheathing = 152,
    CustomCableSparkTest = 153,
    CustomCableCableMarking = 154,
    CustomCableSpooler = 155,
    Stitching = 165,
    RubberExtrusion = 166,
    //WireCuttingTermination = 166666,
    Passivation = 173,
    WeldingPreparation = 176,
    WeldingCleaning = 177,
    CleaningForging = 198,
    MaterialKitting = 182,
    ThroughHoleLine = 183,
    InCircuitTestProgramming = 184,
    Coating = 185,
    AdhesivePotting = 186,
    RoutingVScoring = 187,
    FunctionalTest = 188,
    LabellingnternalPackaging = 189,
    BarCodeReader = 190,
    SMTLine = 191,
    ElectronicsLaserMarking = 196,
    ElectronicsVisualInspection = 197,
    Testing = 199,
    Straightening = 200,
    Control = 201,
    LubricationPhosphating = 208,
    BilletHeating = 211,
    TrimmingPressForging = 212,
    TubeBending = 213,
    RubberFeltSheetCutting = 215,
    RubberFeltSheetStacking = 216,
    SeamStiching = 217,
    SeamWelding = 218,
    Brazing = 220,
    BearingPressing = 221,
    IngotBandSawCutting = 223,
    MetalExtrusion = 224,
    CutToLength = 225,
    PlasticTubeExtrusion = 226,
    PlasticConvolutedTubeExtrusion = 247,
    PlasticVacuumForming = 72,
    InnerLayer = 227,
    LaminationBonding = 228,
    PCBDrilling = 229,
    PCBPlating = 230,
    OuterLayer = 231,
    Soldermask = 232,
    SilkScreen = 233,
    SurfaceFinish = 234,
    RoutingScoring = 235,
    ETestBBT = 236,
    Shearing = 268,
    Cutting = 237,
    MaterialInspectionElectronics = 238,
    CuttingMachineElectronics = 239,
    CornersShaping = 240,
    AutomaticPCStacker = 241,
    Grind = 242,
    InspectionElectronics = 243,
    Baking = 244,
    WashingElectronics = 245,
    FQCInspection = 246,
    // PlasticConvolutedTubeManufacturing = 247,
    ManualDeflashing = 248,
    RubberInjectionMolding = 249,
    RubberInjectionMoldingDoubleShot = 250,
    //ReeltoReelPlating = 251,
    Pointing = 252,
    ConnectorAssemblyPlastics = 253,
    CleaningProcess = 254,
    PlasticRotorMolding = 255,
    TwinSheetForming = 256,
    CuttingandTrimming = 257,
    ScreenPrinting = 258,
    SilkPrinting = 259,
    VacuumCleaning = 260,
    RollBending = 261,
    Wirebendingandcutting = 262,
    TubeLaser = 263,
    TubeBendingMetal = 264,
    TransferPress = 265,
    Piercing = 266,
    //TransferPress=267,
    //CuttingShearing=268,
    CuttingShearing = 269,
    ImpedanceCouponTest = 270,
    DyePenetrantTest = 271,
    MagneticParticleTest = 272,
    BodyEndsOnly = 273,
    PMICertificateOfCompliance = 274,
    HardnessTest = 275,
    MicroStructureTest = 276,
    WitnessPouringTestForBodyBonnet = 277,
    FerriteContentTestSSTest = 278,
    ImpactTest = 279,
    PittingCorrosionTest = 280,
    IGCBodyBonnetTest = 281,
    Hydrotest = 282,
    ConduitTubeSleeveHSTPreparation = 283,
    FunctionalTestCableHarness = 284,
    EMPartAssemblyTesting = 285,
    BilletHeatingContinuousFurnace = 290,
    PostCuring = 353,
    CopperPlating = 354,
    EVAFilm = 355,
    Sand3DPrinting = 356,
    PlugConnectorOvermolding = 357,
    CMMInspection = 210,
    Preform = 360,
}

export enum StampingType {
    BlankingPunching = 1,
    Forming = 2,
    Drawing = 3,
    Bending = 4,
    Piercing = 5,
    Coining = 6,
    Compound = 7,
    Restrike = 8,
    // Transfer Press
    ShallowDrawRect = 9,
    RedrawRect = 10,
    Trimming = 11,
    ShallowDrawCir = 12,
    RedrawCir = 13,
}

export enum PrimaryProcessType {
    // material
    InjectionMouldingDoubleShot = 1,
    InjectionMouldingSingleShot = 2,
    BlowMoulding = 3,
    CompressionMoulding = 4,
    TransferMolding = 6,
    ThermoForming = 7,
    LaserCutting = 10,
    OxyCutting = 11,
    PlasmaCutting = 12,
    WaterjetCutting = 13,
    StampingProgressive = 14,
    StampingStage = 15,
    TurretPunch = 16,
    HPDCCasting = 17,
    LPDCCasting = 18,
    GDCCasting = 19,
    GreenCastingAuto = 20,
    GreenCastingSemiAuto = 68,
    ColdForgingClosedDieHot = 23,
    ColdForgingColdHeading = 24,
    WeldingGMAW = 61000, // not found in db
    HotForgingClosedDieHot = 25,
    HotForgingOpenDieHot = 26,
    WiringHarness = 37,
    CableAssembly = 46,
    Assembly = 69,
    Painting = 53,
    Plating = 54,
    PowderCoating = 55,
    Printing = 56,
    MigWelding = 57,
    TigWelding = 58,
    SpotWelding = 77,
    StickWelding = 78,
    WetPainting = 59,
    ZincPlating = 60,
    ChromePlating = 61,
    NoBakeCasting = 62,
    InvestmentCasting = 21,
    ShellCasting = 22,
    VProcessSandCasting = 113,
    Sand3DPrinting = 114,
    NickelPlating = 63,
    CopperPlating = 112,
    TinPlating = 64,
    GoldPlating = 66,
    SilverPlating = 67,
    R2RPlating = 96,
    CustomizeCable = 65,
    ConnectorAssembly = 70,
    WireCuttingTermination = 71,
    RubberExtrusion = 48,
    SiliconCoatingAuto = 73,
    SiliconCoatingSemi = 74,
    Galvanization = 75,
    MetalTubeExtrusion = 49,
    ConventionalPCB = 84,
    HDIPCB = 85,
    TubeBending = 86,
    InsulationJacket = 87,
    SeamWelding = 88,
    Brazing = 90,
    MetalExtrusion = 91,
    PlasticTubeExtrusion = 92,
    PlasticVacuumForming = 8,
    RigidFlexPCB = 100,
    TransferPress = 102,
    SemiRigidFlex = 104,
    Electronics = 105,
    RubberInjectionMolding = 94,
    RoundBar = 51,
    RectangularBar = 43,
    RoundTube = 41,
    TubeLaserCutting = 116,
}

export enum MachineType {
    Automatic = 1,
    SemiAuto = 2,
    Manual = 3,
}
export enum MachineTypeName {
    Automatic = 'Automatic',
    SemiAuto = 'Semi-Automatic',
    Manual = 'Manual',
}

export const MachineTypePercentage = {
    [MachineType.Automatic]: {
        [MachineType.Automatic]: 1,
        [MachineType.SemiAuto]: 0.92,
        [MachineType.Manual]: 0.8,
    },
    [MachineType.SemiAuto]: {
        [MachineType.Automatic]: 1.25,
        [MachineType.SemiAuto]: 1.15,
        [MachineType.Manual]: 1,
    },
    [MachineType.Manual]: {
        [MachineType.Automatic]: 1.25,
        [MachineType.SemiAuto]: 1.15,
        [MachineType.Manual]: 1,
    },
};

export enum MachiningTypes {
    Rod = 51, // Round bar
    Tube = 41, // Round tube
    SquareBar = 42,
    RectangularBar = 43,
    HexagonalBar = 44,
    Block = 58,
    Wire = 45,
    OtherShapes = 46,
    LAngle = 79,
    IBeam = 80,
    Channel = 81,
    WBeams = 82,
    HSS = 83,
}

export enum BendingToolTypes {
    Soft = 1,
    Dedicated = 2,
}

export enum OHPCategory {
    CategoryA = 0,
    Category = 1,
}

export enum PackingMode {
    Reusable = 0,
    NonReusable = 1,
    NoPacking = 2,
}

export enum PartType {
    ChildPart = 0,
    Assembly = 1,
    SubAssesmbly = 2,
}
