export class DeburringConfigService {
  getDeburringLookupData() {
    let resultList: any[] = [];
    resultList = [
      { Material: ['Carbon Steel', 'Hot Rolled Steel', 'Cold Rolled Steel', 'Mild Steel', 'Galvanized Steel', 'Cold heading steel'], OperatingSpeed: 6000, Speed: 1 },
      { Material: ['Hardened Steel', 'Alloy Steel', 'High Carbon Bearing steel', 'Tool Steel'], OperatingSpeed: 4000, Speed: 0.7 },
      { Material: ['Stainless Steel', 'Silicon Steel', 'Spring Steel'], OperatingSpeed: 3000, Speed: 0.5 },
      { Material: ['Cast Iron', 'Cast Steel', 'Sand'], OperatingSpeed: 2500, Speed: 0.4 },
      { Material: ['Titanium', 'Gold', 'Graphite', 'Lead', 'Lead alloy', 'Leaded Red Brass Alloy', 'Magnesium Alloy', 'Manganese Bronze Alloy', 'Tungsten Carbide'], OperatingSpeed: 5000, Speed: 0.8 },
      { Material: ['Nickel', 'Nickel & Nickel Alloy', 'Nickel Alloy', 'Nickel Iron', 'Niobium', 'Tin', 'Zinc', 'Zinc & Zinc Alloy', 'Zinc+Nickel'], OperatingSpeed: 5000, Speed: 0.8 },
      { Material: ['Copper'], OperatingSpeed: 4000, Speed: 0.7 },
      { Material: ['Copper', 'Copper Alloy', 'Bronze Alloy', 'Bronze and Bronze alloy'], OperatingSpeed: 4000, Speed: 0.7 },
      { Material: ['Aluminium'], OperatingSpeed: 8000, Speed: 1.3 },
      {
        Material: [
          'Plastic',
          'ABS',
          'Acrylic Coat',
          'Butadiene-(BR-Polybutadiene)',
          'Additive-Carbon Black-(Additive-Carbon Black)',
          'Alphatic Polyurethane Top Coat',
          'Antimony',
          'BIIR-(Bromobutyl Rubber)',
          'Bismuth',
          'Bobbin paper',
          'Cardboard',
          'Carton Box',
          'Chromium',
          'Chloroprene / Neoprene-(CR – POLYCHLOROPRENE (NEOPRENE))',
          'Compound Rubber-()',
          'Plastic Consumale',
          'Cork',
          'corrugated',
          'Corrugated Paper',
          'Duplex board',
          'Duplex board grey back',
          'EPDM-(Ethylene-Propylene Terpolymer Rubber)',
          'Epichlorohydrin(ECO)-( Epichlorohydrin)',
          'Epoxy Coat',
          'ESD Cover',
          'Ethylene Vinyl Acetate',
          'Fluorous-(Fluoro elastomer rubber)',
          'High Solids Epoxy Coating',
          'HIPS',
          'Individual Pack',
          'Inorganic Zinc Silicate Primer',
          'Isoprene-(Poly Isoprene)',
          'Ivory board',
          'Kraft Paper',
          'Label Paper',
          'LCP',
          'Melt Processable Rubber(MPR)-(Melt Processable Rubber)',
          'Natural - Standard Rubber-()',
          'Neoprene-EPDM-SBR Blend-(Neoprene-EPDM-SBR Blend)',
          'Nitrile Rubber',
          'None',
          'Nylon(PA)',
          'PA6T',
          'PA9T',
          'Painting',
          'Palladium',
          'Paper',
          'Paper Pulp/Chemical mechanical group',
          'part Envelop',
          'PBT',
          'PBT+ASA',
          'PBT+PET',
          'PC',
          'PE',
          'PE Cover',
          'PEEK',
          'PET',
          'PETG',
          'Pinewood',
          'Plywood',
          'PMMA',
          'PMMA(Acrylic)',
          'Polybutadiene-(Polybutadiene (BR))',
          'Polyester-(Polyester)',
          'Polytetrafluoroethylene (PTFE)',
          'POM(Acetal)',
          'Powder Coating',
          'PP',
          'PPE',
          'PPE+PA',
          'PPS',
          'PS',
          'PSU - Polysulfone',
          'PU',
          'PVC',
          'PVC Strip',
          'PVF',
          'Recycled Pulp',
          'Recycled Rubber-(Recycled Rubber)',
          'SBR-(Styrene Butadiene Rubber)',
          'SBS-(Styrene Butadiene Styrene)',
          'Shrink Wrap',
          'Silicone Coating',
          'Silicone Oil-(Silicone Oil)',
          'Silicone Rubber',
          'Silicone-(Silicone)',
          'Tetragonal Zirconia Polycrystal (TZP)',
          'TPE',
          'TPO - Thermoplastic Polyolefin',
          'Vaccuum Tray',
          'White Board',
          'White Carbon Black-(White Carbon Black)',
          'White Cardboard',
          'Wooden Pallet',
        ],
        OperatingSpeed: 10000,
        Speed: 1.7,
      },
    ];
    return resultList;
  }
}
